import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-big-calendar/lib/css/react-big-calendar.css";
import Provider from "@/components/providers/Provider";
import Navbar from "@/components/Navbar";
import Modal from "@/components/Modals/Modal";
import AppointmentForm from "@/components/Form/AppointmentForm";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Appointment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-background text-text-black overflow-x-hidden`}
      >
        <Navbar />
        <Provider>
          {children}
        <Modal/>
          </Provider>
      </body>
    </html>
  );
}
