import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import Provider from "@/components/providers/Provider";
import CalendarHeader from "@/components/Appointment/CalendarHeader";

import ContextWrapper from "@/components/Appointment/Context/ContextWrapper";
import { useAppointmentSlice } from "@/store/Appointment/zustand";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <CalendarHeader/>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
